Repository depromeet/kok-client, pull requests merged in 2025-03, with the labels that each got.

#14 design(ui): button 컴포넌트 구현
  apps/web/next.config.ts
  apps/web/package.json
  apps/web/src/assets/icons/add-icon.tsx
  apps/web/src/components/test/Test.tsx
  packages/ui/package.json
  packages/ui/src/button.tsx
  packages/ui/src/card.tsx
  packages/ui/src/code.tsx
  packages/ui/src/common/button/index.tsx
  packages/ui/src/common/button/style.css.ts
  packages/ui/src/common/index.ts
  pnpm-lock.yaml
Labels: P1, P2, P3

#16 design(ui): Text 컴포넌트 구현
  apps/web/src/components/test/Test.tsx
  packages/ui/src/components/button/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/components/text/index.tsx
  packages/ui/src/components/text/style.css.ts
  packages/ui/src/utils/index.ts
Labels: P1, P3

#17 design(ui): Flex 컴포넌트 구현
  apps/web/src/components/test/Test.tsx
  packages/ui/src/components/flex/index.tsx
  packages/ui/src/components/flex/style.css.ts
  packages/ui/src/components/index.ts
Labels: P2, P3

#18 design(ui): Input 컴포넌트 구현
  apps/web/src/components/test/Test.tsx
  packages/ui/package.json
  packages/ui/src/components/index.ts
  packages/ui/src/components/input/index.tsx
  packages/ui/src/components/input/style.css.ts
  packages/ui/src/icons/DeleteIcon.tsx
  packages/ui/src/icons/SearchIcon.tsx
  packages/ui/src/icons/index.ts
  packages/ui/src/tokens/colors.ts
Labels: P1, P2

#47 feat: 공통UI 애니메이션 바텀 시트 구현 및 적용
  apps/web/src/components/midpoint-result/FindingMidPoint.tsx
  apps/web/src/components/midpoint-result/MidPointResult.tsx
  apps/web/src/components/midpoint-result/organisms/ParticipantBottomSheet.tsx
  apps/web/src/components/midpoint-result/organisms/ResultBanner.tsx
  apps/web/src/components/midpoint-result/organisms/ResultBottomSheet.tsx
  packages/naver-map/src/DotMarker.tsx
  packages/naver-map/src/Polygon.tsx
  packages/ui/src/components/bottom-sheet/AnimationBottomSheet.tsx
  packages/ui/src/components/bottom-sheet/index.tsx
  packages/ui/src/components/bottom-sheet/style.css.ts
  packages/ui/src/tokens/colors.ts
Labels: P2, P3

#52 feat(ui) : 공통 배너 구현
  apps/web/src/assets/icons/SmallMidIcon.tsx
  apps/web/src/components/midpoint-result/FindingMidPoint.tsx
  apps/web/src/components/midpoint-result/organisms/MapHeader.tsx
  apps/web/src/components/midpoint-result/organisms/ParticipantBottomSheet.tsx
  apps/web/src/components/midpoint-result/organisms/RefreshCenterButton.tsx
  apps/web/src/components/midpoint-result/organisms/ResultBanner.tsx
  apps/web/src/components/midpoint-result/organisms/ResultBottomSheet.tsx
  apps/web/src/components/midpoint-result/organisms/StartBanner.tsx
  apps/web/src/components/midpoint-result/organisms/styles.css.ts
  apps/web/src/components/midpoint-result/style.css.ts
  packages/ui/src/components/banner/Banner.tsx
  packages/ui/src/components/banner/index.ts
  packages/ui/src/components/banner/styles.css.ts
  packages/ui/src/components/index.ts
  packages/ui/src/icons/SmallMidIcon.tsx
  packages/ui/src/icons/index.ts
Labels: P1, P3

#53 feat(web) : 약속방 생성 API 연결 및 테스트 완료
  apps/web/src/api/controllers/room.controller.ts
  apps/web/src/api/types/create-room/index.type.ts
  apps/web/src/components/create-room/templates/CreateRoomLayout.tsx
  apps/web/src/constants/api/index.ts
  apps/web/src/hooks/api/useCreateRoom.ts
Labels: P2

#63 feat(api, ui): 결과 화면 - 대중교통 경로 UI 구현, API 연동
  apps/web/src/api/controllers/location.controller.ts
  apps/web/src/api/types/location/location.types.ts
  apps/web/src/components/midpoint-result/FindingMidPoint.tsx
  apps/web/src/components/midpoint-result/MidPointResult.tsx
  apps/web/src/components/midpoint-result/atom/transport-icon/TransportIcon.tsx
  apps/web/src/components/midpoint-result/organisms/ResultBanner.tsx
  apps/web/src/components/midpoint-result/organisms/ResultBottomSheet.tsx
  apps/web/src/components/midpoint-result/organisms/ResultPattern.tsx
  apps/web/src/components/midpoint-result/organisms/TransporBar.tsx
  apps/web/src/components/midpoint-result/organisms/styles.css.ts
  apps/web/src/constants/api/index.ts
  apps/web/src/hooks/api/useLocation.ts
  apps/web/src/hooks/api/useRecommendStation.ts
  apps/web/src/hooks/api/useTransfer.ts
  apps/web/src/utils/location.ts
  apps/web/src/utils/meterToKilometers.ts
  apps/web/src/utils/subway.ts
  apps/web/src/utils/time.ts
  packages/naver-map/src/DotMarker.tsx
  packages/naver-map/src/NaverMap.tsx
  packages/naver-map/src/types.ts
  packages/ui/src/components/text/style.css.ts
Labels: P3

#65 feat: 실시간 중간 장소 화면에 카카오톡 공유 연동
  apps/web/src/components/midpoint-result/FindingMidPoint.tsx
  apps/web/src/components/midpoint-result/organisms/ParticipantBottomSheet.tsx
  apps/web/src/components/share-room/molecule/KakaoTalkShareButton.tsx
  apps/web/src/components/share-room/organisms/share-room-bottom/ShareRoomBottom.tsx
  apps/web/src/constants/kakao-template/index.ts
  packages/ui/src/components/banner/Banner.tsx
  packages/ui/src/components/banner/Mascot.tsx
Labels: P2

#80 feat: 리더 위치 표시 및 출발지 관리 기능 구현
  apps/web/src/api/types/room/index.type.ts
  apps/web/src/components/midpoint-result/FindingMidPoint.tsx
  apps/web/src/components/midpoint-result/organisms/ParticipantBottomSheet.tsx
  apps/web/src/components/midpoint-result/organisms/RefreshCenterButton.tsx
  apps/web/src/components/midpoint-result/organisms/StartBanner.tsx
  apps/web/src/components/midpoint-result/organisms/styles.css.ts
  apps/web/src/components/search-place-bottom-sheet/index.tsx
  apps/web/src/hooks/api/useLocation.ts
  apps/web/src/hooks/api/useStartLocation.ts
  packages/naver-map/src/DotMarker.tsx
  packages/naver-map/src/Marker.tsx
  packages/naver-map/src/NaverMap.tsx
  packages/naver-map/src/ProfileMarker.tsx
  packages/naver-map/src/types.ts
  packages/ui/src/components/banner/Banner.tsx
Labels: P2, P3

#91 feat: 결과 화면 ui 수정
  apps/web/src/components/midpoint-result/organisms/ResultBottomSheet.tsx
  apps/web/src/components/midpoint-result/organisms/ResultPattern.tsx
  apps/web/src/components/midpoint-result/organisms/TransporBar.tsx
  apps/web/src/components/midpoint-result/organisms/styles.css.ts
Labels: P3

#95 feat(share): 스켈레톤 UI 및 투표 모드 구현
  apps/web/src/api/types/room/index.type.ts
  apps/web/src/components/midpoint-result/FindingMidPoint.tsx
  apps/web/src/components/midpoint-result/atom/share/ShareIcon.tsx
  apps/web/src/components/midpoint-result/organisms/MapHeader.tsx
  apps/web/src/components/midpoint-result/organisms/ParticipantBottomSheet.tsx
  apps/web/src/components/midpoint-result/organisms/RefreshCenterButton.tsx
  apps/web/src/components/midpoint-result/organisms/ResultPattern.tsx
  apps/web/src/components/midpoint-result/organisms/StartBanner.tsx
  apps/web/src/components/midpoint-result/organisms/styles.css.ts
  apps/web/src/components/midpoint-result/style.css.ts
  apps/web/src/components/profile-list/organisms/profile-list-footer/ProfileListFooter.tsx
  apps/web/src/components/share-room/molecule/KakaoTalkShareButton.tsx
  apps/web/src/hooks/api/useRoomInfo.ts
  packages/ui/src/components/banner/Banner.tsx
  packages/ui/src/components/bottom-sheet/AnimationBottomSheet.tsx
  packages/ui/src/components/button/style.css.ts
Labels: P2, P3
